

paths:
  mimic_dir: &mimic_dir datasets/mimic3/csv
  static_dir: &static_dir datasets/mimic3/static
  dataset_dir: &dataset_dir datasets/mimic3_full
  word2vec_dir: &word2vec_dir datasets/mimic3_full/word2vec

preprocessing:
  name: mimic_iii_preprocessing_pipeline
  params:
    paths:
      mimic_dir: *mimic_dir
      static_dir: *static_dir
      save_dir: *dataset_dir
      diagnosis_code_csv_name: DIAGNOSES_ICD.csv.gz
      procedure_code_csv_name: PROCEDURES_ICD.csv.gz
      noteevents_csv_name: NOTEEVENTS.csv.gz
      prescriptions_csv_name: PRESCRIPTIONS.csv.gz
      microbiology_events_csv_name: MICROBIOLOGYEVENTS.csv.gz
      train_json_name: train.json
      val_json_name: val.json
      test_json_name: test.json
      label_json_name: labels.json
      label_freq_json_name: label_freq.json
    dataset_metadata:
      column_names:
        subject_id: SUBJECT_ID
        hadm_id: HADM_ID
        category: CATEGORY
        text: TEXT
        icd9_code: ICD9_CODE
        labels: LABELS
        drug_type: DRUG_TYPE
        drug: DRUG
        prod_strength: PROD_STRENGTH
        dose_val_rx: DOSE_VAL_RX
        route: ROUTE
        org_itemid: ORG_ITEMID
        ad_itemid: AB_ITEMID
        dilution_value: DILUTION_VALUE
        interpretation: INTERPRETATION
    dataset_splitting_method:
      name: caml_official_split
      params:
        hadm_dir: *static_dir
        train_hadm_ids_name: train_full_hadm_ids.json
        val_hadm_ids_name: dev_full_hadm_ids.json
        test_hadm_ids_name: test_full_hadm_ids.json
    clinical_note_preprocessing:
      to_lower:
        perform: true
      remove_punctuation:
        perform: true
      remove_numeric:
        perform: true
        replace_numerics_with_letter: null
      remove_stopwords:
        perform: true
        params:
          stopwords_file_path: null
          remove_common_medical_terms: false
      stem_or_lemmatize:
        perform: true
        params:
          stemmer_name: nltk.WordNetLemmatizer
      truncate:
        perform: true
        params:
          max_length: 1500
    retain_section_headers: true
    incorrect_code_loading: false
    count_duplicate_codes: false
    code_preprocessing:
      top_k: 0
      code_type: both
      add_period_in_correct_pos:
        perform: true
      rare_subset: false
    structured:
      categorical_fields: [DRUG_TYPE, DRUG, PROD_STRENGTH, ROUTE, ORG_ITEMID, AB_ITEMID, INTERPRETATION]
      numerical_fields: [DOSE_VAL_RX, DILUTION_VALUE]
    train_embed_with_all_split: false
    tokenizer:
      name: spacetokenizer
      params: null
    embedding:
      name: word2vec
      params:
        embedding_dir: *word2vec_dir
        pad_token: "<pad>"
        unk_token: "<unk>"
        word2vec_params:
          vector_size: 100
          min_count: 3
          epochs: 5
